// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.dagger.hilt.android) apply false
    alias(libs.plugins.dokka) apply false
    alias(libs.plugins.dokka.javadoc) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.kapt) apply false
    alias(libs.plugins.maven.publish)
    // TODO: Dagger’s KSP support is currently in alpha, see: https://dagger.dev/dev-guide/ksp
    // alias(libs.plugins.ksp) apply false
}

def localProperties = new Properties().tap {
    if (file("local.properties").exists()) {
        it.load(file("local.properties").newInputStream())
    }
}

subprojects {
    apply plugin: "maven-publish"
    apply plugin: "org.jetbrains.dokka"
    apply plugin: "org.jetbrains.dokka-javadoc"

    afterEvaluate {
        if (!it.plugins.hasPlugin("com.android.library")) return

        tasks.register('androidSourcesJar', Jar) {
            getArchiveClassifier().set('sources')
            from android.sourceSets.main.java.source
        }

        tasks.register('dokkaJavadocJar', Jar) {
            dependsOn dokkaGeneratePublicationJavadoc
            getArchiveClassifier().set('javadoc')
            from dokkaGeneratePublicationJavadoc.outputDirectory
        }
        tasks.register('dokkaHtmlJar', Jar) {
            dependsOn dokkaGeneratePublicationHtml
            getArchiveClassifier().set('html-doc')
            from dokkaGeneratePublicationHtml.outputDirectory
        }

        artifacts {
            archives androidSourcesJar
            archives dokkaJavadocJar
            archives dokkaHtmlJar
        }

        publishing {
            repositories {
                maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/PnX-SI/gn_mobile_maps")
                    credentials {
                        username = localProperties.get("gpr.user") ?: System.getenv("USERNAME")
                        password = localProperties.get("gpr.key") ?: System.getenv("TOKEN")
                    }
                }
            }
            publications {
                gpr(MavenPublication) {
                    artifact(layout.buildDirectory.file("outputs/aar/${project.name}-release.aar")) {
                        builtBy tasks.matching { it.name == "bundleReleaseAar" }
                    }
                    artifact androidSourcesJar
                    artifact dokkaJavadocJar
                    artifact dokkaHtmlJar
                    groupId = 'fr.geonature'
                    artifactId = project.name
                    version = project.findProperty('version') ?: '0.0.1'

                    pom {
                        name = 'GeoNature Android maps library'
                        description = 'Small Android Map library based on osmdroid'
                        url = 'https://github.com/PnX-SI/gn_mobile_maps'

                        licenses {
                            license {
                                name = 'GNU General Public License version 3.0'
                                url = 'https://www.gnu.org/licenses/gpl-3.0.txt'
                            }
                        }

                        developers {
                            developer {
                                id = 'sgrimault'
                                name = 'Sebastien GRIMAULT'
                                email = 'sebastien.grimault@gmail.com'
                            }
                        }
                    }
                }
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

private File loadVersionPropertiesFile(String moduleName) {
    def versionPropsFile = file("$moduleName/version.properties")

    println "reading '${versionPropsFile.name}' for module '$moduleName' ..."

    if (!versionPropsFile.exists()) {
        versionPropsFile.createNewFile()
    }

    return versionPropsFile
}

@SuppressWarnings("unused")
int updateVersionCode(moduleName) {
    File propertiesFile = loadVersionPropertiesFile(moduleName)

    Properties versionProperties = new Properties()
    versionProperties.load(new FileInputStream(propertiesFile))

    int versionCode = Integer.parseInt(versionProperties.getProperty('VERSION_CODE', '0').toString()).intValue() + 1

    versionProperties['VERSION_CODE'] = versionCode.toString()
    versionProperties.store(propertiesFile.newWriter(), null)

    println "version code: $versionCode"

    return versionCode
}

@SuppressWarnings("unused")
def readKeystoreProperties(moduleName) {
    def propertiesFile = rootProject.file('keystore.properties')
    def configName = 'release'

    println "reading '${propertiesFile.absolutePath}' for module '$moduleName' ..."

    Project moduleProject = project.project(moduleName)

    if (propertiesFile.exists() && moduleProject.hasProperty("android") && moduleProject.android.signingConfigs.hasProperty(configName)) {
        def props = new Properties()
        props.load(new FileInputStream(propertiesFile))

        moduleProject.android.signingConfigs[configName].storeFile = file(props['STORE_FILE'])
        moduleProject.android.signingConfigs[configName].storePassword = props['STORE_PASSWORD']
        moduleProject.android.signingConfigs[configName].keyAlias = props['KEY_ALIAS']
        moduleProject.android.signingConfigs[configName].keyPassword = props['KEY_PASSWORD']

        println 'done'
    }
}
